### PR TITLE
Add "Upcoming events" and "Twitter"  section 

### PR DESCRIPTION
**Pull request by ritot**
Still a work in progress, but I think I got most of it down.

- Added placeholder `About` component
- Added `Upcoming events` and `Twitter` components, which are side-by-side and grouped as `News`
- Added parallax effect for `News` to divide the team page into sections

TODO:

- [x] Should the Events component stretch out until it's the same length as the Twitter component?
- [x] Make it responsive for mobile (stack Events and Twitter)
- [x] Feel like the overall design of the two components could look better

### CODE REVIEW

**Comment by alansun25** [comment]
@ritot Good start!! I'm not sure how I feel about having the news background be transparent, though that may change depending on how the about section looks.

> Should the Events component stretch out until it's the same length as the Twitter component?

I don't think so. IMO what would look better is to not make the two components stretch to fit the entire width of the container. Instead, put a smaller width div within the main News div so that there's less white space in upcoming events, and users don't have to move their eyes across the entire width of the screen to see the Twitter feed. Maybe the upcoming events component can be the same width as the Twitter feed component.

Also, each event currently has a rounded border around its entire border. I think it might look better to just have divides between the events rather than have the whole border be colored in. Let me know what you think.

If any of this is confusing send me a text!

**Comment by ritot** [comment]
@alansun25 Thanks for your feedback!

> I'm not sure how I feel about having the news background be transparent, though that may change depending on how the about section looks.

Yeah I wasn't sure whether to just make it a white background, purple like the roster, or transparent. Once we have the about section we can discuss how we want to style everything so they fit together!

> Maybe the upcoming events component can be the same width as the Twitter feed component.

That's a good idea, will do 🙆

> I think it might look better to just have divides between the events rather than have the whole border be colored in

Do you mean like in the old website like this? The twitter component can only be white or dark, so if we want something similar, the background will have to match that.
Screen Shot 2021-09-05 at 5 46 21 PM

**Comment by alansun25** [comment]
@ritot Yeah you see how the events just have divides between them rather than all have a rounded border? That's basically what I meant.

**Comment by alansun25** [comment]
> Yeah I wasn't sure whether to just make it a white background, purple like the roster, or transparent. Once we have the about section we can discuss how we want to style everything so they fit together!

We probably can't make it white because the text on the fixed navbar is white (unless we figure out how to change the background color when the user scrolls to the About section)

**Review by alansun25 — COMMENTED** [review]
I would add a min-h-screen tailwind class to the main div holding the new section so that the news section fills the entire screen (like how the landing page does).

**Comment by ritot** [comment]
@alansun25 this PR also brings LaWUFA's page up to date with WUFO's

**Review by alansun25 — APPROVED** [review]
Looks great, I actually really like the transparent background here. Are the WUFA and WUFO events supposed to be the exact same?

**Comment by ritot** [comment]
> Are the WUFA and WUFO events supposed to be the exact same?

Yeah for the moment, but we can easily change it by editing `lawufa-events.js`

**Pull request merged**
